### ISSUE TITLE
"lnvm_test: LightNVM not enabled!"

### ISSUE THREAD

**Issue by Carl-LQ** [OpenChannelSSD/lightnvm-hw#2]
Hi experts,
I'm trying to run the sanity test, and part of the output of 'python lnvm_test.py -h' is 
"-d DEVICE, --device DEVICE
                        Choose device to create LightNVM target from.
                        Supported devices can be seeing executing: 'cat
                        /sys/module/lnvm/parameters/configure_debug'. This
                        argument is mandatory. "
The problem is that there isn't the directory /sys/module/lnvm/. So when I tried to run the lnvm_test.py, there comes a prompt: "lnvm_test: LightNVM not enabled!". I read the codes and found these:
lnvm_config = '/sys/module/lnvm/parameters/configure_debug'
if not os.path.exists(lnvm_config):
    print ("lnvm_test: LightNVM not enabled!")
    return
Therefore, it seems there is something wrong with my environment so there is no /sys/module/lnvm/parameters/configure_debug in my computer. But I have no idea how to solve the problem. I think I have set up the environment correctly. Could you please tell me what to do?  Any idea would be grateful. Thank you.

**Comment by javigon** [comment]
Hi Carl,

This repository is outdated. Apologies.

Please follow these instructions to bring up pblk [1].

Please let us knows if this solves the issue.

Thanks,
Javier

[1] http://lightnvm.io/pblk-tools/usage.html

**Comment by Carl-LQ** [comment]
Hi Javigon,
Thank you for your instructions! I didn't know it's outdated. And now I follow the instructions and it worked! Thank you again!

Sincerely,
Carl

**Comment by javigon** [comment]
Great. I'll close the issue then.
